name: Upload changed template to S3

on:
  push:
    branches:
      - main
    paths:
      - aws/cloudformation/ec2-rds-s3/kestra-oss.yaml

env:
  TEMPLATE1: aws/cloudformation/ec2-rds-s3/kestra-oss.yaml
  BUCKET_NAME: kestra-deployment-templates
  AWS_REGION: eu-west-1

jobs:
  upload:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository (full history)
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-west-1

      - name: Sync only listed files
        run: |
            aws s3 sync . "s3://${{ env.BUCKET_NAME }}/" \
            --acl public-read \
            --exact-timestamps \
            --exclude "*" \
            --include "${{ env.TEMPLATE1 }}" \
